import palette from "./palette";

export default {
  h1: {
    // color: palette.text.primary,
    // fontSize: "46px",
    // fontWeight: 700,
    // lineWeight: "56px",
    // letterSpacing: "0em",
    // textAlign: "left",

    fontFamily: "Montserrat",
    fontSize: "46px",
    fontWeight: 700,
    lineHeight: "56px",
    letterSpacing: "0em",
    textAlign: "left",
  },
  h2: {
    color: palette.text.primary,
    fontWeight: 500,
    fontSize: "29px",
    letterSpacing: "-0.24px",
    lineHeight: "32px",
  },
  h3: {
    Font: "Montserrat",

    color: palette.text.primary,
    fontWeight: "700",
    fontSize: "12px",
    letterSpacing: "-0.06px",
    lineHeight: "14.63px",
    fontFamily: "Montserrat",
  },
  h4: {
    color: palette.text.primary,
    fontWeight: 700,
    fontSize: "30px",
    letterSpacing: "-0.06px",
    lineHeight: "43.88px",
    fontFamily: "Montserrat",
  },
  h5: {
    color: palette.text.primary,
    fontWeight: 550,
    fontSize: "16px",
    letterSpacing: "-0.05px",
    lineHeight: "20px",
    fontFamily: "Montserrat",
  },
  h6: {
    color: palette.text.primary,
    fontWeight: 500,
    fontSize: "12px",
    letterSpacing: "-0.05px",
    lineHeight: "14.63px",
    fontFamily: "Montserrat",
  },
  subtitle1: {
    color: palette.text.primary,
    fontSize: " 36px",
    letterSpacing: "0em",
    lineHeight: "20px",
    fontFamily: "Montserrat",
    fontStyle: "normal",
    textAlign: "left",
    fontWeight: 300,
  },
  subtitle2: {
    color: palette.text.secondary,
    fontWeight: 400,
    fontSize: "14px",
    letterSpacing: "-0.05px",
    lineHeight: "21px",
  },
  body1: {
    color: palette.text.primary,
    fontSize: "20px",
    letterSpacing: "-0.05px",
    lineHeight: "21px",
    fontFamily: "Montserrat",

    fontWeight: 300,
    lineHeight: "21px",
    letterSpacing: "0em",
  },
  body2: {
    color: palette.text.secondary,
    fontSize: "12px",
    letterSpacing: "-0.04px",
    lineHeight: "18px",
  },
  button: {
    color: palette.text.primary,
    fontSize: "14px",
  },
  caption: {
    color: palette.text.secondary,
    fontSize: "11px",
    letterSpacing: "0.33px",
    lineHeight: "13px",
  },
  overline: {
    color: palette.text.secondary,
    fontSize: "11px",
    fontWeight: 500,
    letterSpacing: "0.33px",
    lineHeight: "13px",
    textTransform: "uppercase",
  },
};
