import palette from "./palette";

export default {
  h1: {
    fontFamily: "Montserrat",
    fontSize: "30px",
    fontWeight: 700,
    lineHeight: "56px",
    letterSpacing: "0em",
    textAlign: "left",
    background:
      "linear-gradient(91.57deg, #C0B7E8 -1.02%, #8176AF 36.25%),linear-gradient(0deg, #FFFFFF, #FFFFFF)",
    backgroundClip: "text",
    textFillColor: "transparent",
  },
  h1white: {
    color: palette.primary.contrastText,
    fontFamily: "Montserrat",
    fontSize: "30px",
    fontWeight: 700,
    lineHeight: "56px",
    letterSpacing: "0em",
  },
  h2: {
    fontWeight: 500,
    fontSize: "30px",
    letterSpacing: "-0.06px",
    lineHeight: "43.88px",
    fontFamily: "Montserrat",
  },
  h3: {
    fontWeight: "700",
    fontSize: "30px",
    letterSpacing: "-0.06px",
    lineHeight: "14.63px",
    fontFamily: "Montserrat",
    textTransform: "capitalize",
  },
  h4: {
    color: palette.text.primary,
    fontWeight: 500,
    fontSize: "29px",
    letterSpacing: "-0.24px",
    lineHeight: "32px",
    fontFamily: "Montserrat",
    textTransform: "capitalize",
  },
  h5: {
    // color: palette.primary.contrastText,
    fontWeight: "700",
    fontSize: "30px",
    letterSpacing: "-0.06px",
    lineHeight: "14.63px",
    fontFamily: "Montserrat",
    textTransform: "capitalize",
  },
  h6: {
    color: palette.text.primary,
    fontWeight: 500,
    fontSize: "12px",
    letterSpacing: "-0.05px",
    lineHeight: "14.63px",
    fontFamily: "Montserrat",
    textTransform: "capitalize",
  },
  subtitle1: {
    color: palette.text.primary,
    fontSize: " 36px",
    letterSpacing: "0em",
    lineHeight: "20px",
    fontFamily: "Montserrat",
    fontStyle: "normal",
    textAlign: "left",
    fontWeight: 300,
    textTransform: "capitalize",
  },
  subtitle2: {
    color: palette.text.secondary,
    fontWeight: 400,
    fontSize: "14px",
    letterSpacing: "-0.05px",
    lineHeight: "21px",
    textTransform: "capitalize",
  },
  body: {
    fontFamily: "Montserrat",
    fontSize: "20px",
    fontWeight: 400,
    lineHeight: "0",
    letterSpacing: "0em",
  },
  body1: {
    color: "white",
    fontSize: "20px",
    letterSpacing: "-0.05px",
    lineHeight: "21px",
    fontFamily: "Montserrat",
    textTransform: "capitalize",
    fontWeight: 300,
    lineHeight: "21px",
    letterSpacing: "0em",
  },
  body2: {
    color: palette.text.secondary,
    fontSize: "12px",
    letterSpacing: "-0.04px",
    lineHeight: "18px",
  },
  button: {
    color: palette.text.primary,
    fontSize: "14px",
  },
  caption: {
    color: palette.text.secondary,
    fontSize: "11px",
    letterSpacing: "0.33px",
    lineHeight: "13px",
  },
  overline: {
    color: palette.text.secondary,
    fontSize: "11px",
    fontWeight: 500,
    letterSpacing: "0.33px",
    lineHeight: "13px",
    textTransform: "uppercase",
  },
};
